apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvc-deployment1
  labels:
    app: dvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dvc 
  template:
    metadata:
      labels:
        app: dvc 
    spec:
      containers:
      - name: dvc
        image: krishnapoddar0705/mlops-test:v1
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: dvc-service
  labels:
    app: dvc
spec:
  type: NodePort
  ports:
    - port: 5000
      nodePort: 30080
      name: http
  selector:
    app: dvc 
